### ISSUE TITLE
Call update for assetfile fails

### ISSUE THREAD

**Issue by codisms** [fritzy/node-azure-media#5]
When I attempt to set the `IsPrimary` flag on an `assetfile` object, I get the following error:

```
.../node_modules/azure-media/node_modules/verymodel/lib/model.js:442
    merrors = meta.defs[field].validate(meta.data[field]);
```

The reason is that `meta.defs[field].validate` is a boolean instead of a function.  This also occurs if you attempt to call update when setting `IsEncrypted` (or any other boolean field).

Note: This might be a bug inside of VeryModel.

**Comment by fritzy** [comment]
Interesting. I'll take a look.

**Comment by NewETown** [comment]
Also running into this issue, code from VeryModel here:

```
//if we have a VeryValidator to validate against, validate it
                } else if (meta.data.hasOwnProperty(field) && meta.defs[field].hasOwnProperty('validate')) {
                    if (typeof meta.defs[field].validate === 'object' && typeof meta.defs[field].validate.validate === 'function') {
                        merrors = meta.defs[field].validate.validate(meta.data[field]);
                    } else {
                        merrors = meta.defs[field].validate(meta.data[field]);
                    }
```

There doesn't seem to be a case for "Don't validate this object" when there's a property that appears to signal if there needs to be validation or not, seems like a VeryModel bug.

On second thought, this is looking for a 'validate' property. Can we not add the 'validate' property to boolean parameters? E.g. IsPrimary, IsEncrypted, etc

**Comment by furqan-razzaq** [comment]
I am getting the exact same error. And as NewETown mentioned, the code is always assuming that there is a validate method, but in case of IsPrimary or IsEncrypted, there is none. Instead the validate property is a boolean.

**Comment by fritzy** [comment]
I wrote this for a client and haven't maintained it. Do you know of anyone interested in maintaining it?

**Comment by codisms** [comment]
@fritzy Please contact me about this and VeryModel.  I may be interested in taking them over.

**Comment by fritzy** [comment]
@codisms sounds great! VeryModel, however, is still alive and breathing -- I have a pending major update for it. I'm happy to add you as a contributor though. I'll go ahead and give you contributor access on this right now. Feel free to IM me (xmpp/google talk) fritzy@netflint.net or email.

**Comment by codisms** [comment]
This issue is related to VeryModel, so it'll need to be fixed there.  Has it been addressed?

**Comment by fritzy** [comment]
Verymodel 3 moved to joi only validators. (Or something that behaves like joi). I'll have to look more closely at those flags.
