### ISSUE TITLE
Cannot initiate Azure Media Service

### ISSUE THREAD

**Issue by chohanwu-zz** [fritzy/node-azure-media#9]
Hi, fritzy, thanks for your work!
I tried to use it but encounter an error when initiate the service
Error Message:
[Error: options.uri is a required argument]

and here's my code:
var AzureMedia = require('azure-media');

var api = new AzureMedia("{client_id: '[MYACCOUNT]', client_secret: '[SECRETE]'} "); 
api.init(function (err) {
  if(err)
    console.log(err);
  else
    console.log('success');
    // do your work here or after this callback
});

Any comment on this? thank you!

**Comment by fritzy** [comment]
I wrote this for a client and haven't maintained it. Do you know of anyone interested in maintaining it?
